timeout: 3

/NPKernel
    protocol: limine
    path: boot():/boot/npkernel.elf
    module_path: boot():/boot/initramfs.cpio
    resolution: 1920x1080x32
    cmdline: npk.mode=development npk.keyboard=tr
